# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    sshkeymgmt: "#{source_dir}"
  repositories:
    provision:
      repo: "https://github.com/puppetlabs/provision.git"
      branch: "main"
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    concat: "puppetlabs/concat"
    # facts:
    #   repo: "puppetlabs/facts"
    #   ref: "1.0.0"
    # inifile:
    #   repo: "puppetlabs/inifile"
    #   ref: "4.1.0"
    # apt:
    #   repo: "puppetlabs/apt"
    #   ref: "7.3.0"
    # puppet_agent:
    #   repo: "puppetlabs/puppet_agent"
    #   ref: "3.0.2"
    # registry:
    #   repo: "puppetlabs/registry"
    #   ref: "3.1.0"
