---
Gemfile:
  required:
    ':development':
      - gem: 'hiera-puppet-helper'
      - gem: 'net-ssh'
      - gem: 'ed25519'
        version: '>= 1.2'
      - gem: 'bcrypt_pbkdf'
        version: '>= 1.0'
      - gem: 'puppet-lint-security-plugins'
      - gem: 'puppet-strings'
    ':system_tests':
      - gem: 'hiera-puppet-helper'

spec/spec_helper.rb:
  mock_with: ':rspec'
  spec_overrides:
    - 'RSpec.configure do |c|'
    - "  c.hiera_config = File.expand_path(File.join(File.dirname(__FILE__), '/fixtures/hiera/hiera.yaml'))"
    - "  c.after(:suite) do"
    - "    RSpec::Puppet::Coverage.report!(80)"
    - "  end"
    - "end"

appveyor.yml:
  delete: true

.gitlab-ci.yml:
  delete: true

.gitignore:
  paths:
    - /spec/fixtures/litmus_inventory.yaml